# creating a user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "fullName": "Bob Dob",
  "email": "bob@dob.com",
  "username": "bobbydob",
  "password": "secret"
}

###
#log in
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "bobbydob",
  "password": "secret"
}

###
#creating post with caption and image
# replace {{token}} with the token from the login response
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYmJ5ZG9iIiwiaWQiOiI2NWRhODA5YmQ5ZmVkMGNiYjI1YWY5YTYiLCJpYXQiOjE3MDkzNTI3MjUsImV4cCI6MTcwOTM1NjMyNX0.NkY1Lx7Mlb72qTtE4Y9eu4rNmObxVkhsvqiKr1NO-Ew
POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: bearer {{token}}

{
  "caption": "a blue square",
  "imageDataUrl": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIj48cmVjdCBmaWxsPSIjMDBCMUZGIiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIvPjwvc3ZnPg=="
}

###
#creating post with image and no caption (should pass)
# replace {{token}} with the token from the login response
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYmJ5ZG9iIiwiaWQiOiI2NWRhODA5YmQ5ZmVkMGNiYjI1YWY5YTYiLCJpYXQiOjE3MDkzNTI3MjUsImV4cCI6MTcwOTM1NjMyNX0.NkY1Lx7Mlb72qTtE4Y9eu4rNmObxVkhsvqiKr1NO-Ew
POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: bearer {{token}}

{
  "imageDataUrl": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIj48cmVjdCBmaWxsPSIjMDBCMUZGIiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIvPjwvc3ZnPg=="
}

###
#creating post with no image (should fail)
# replace {{token}} with the token from the login response
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYmJ5ZG9iIiwiaWQiOiI2NWRhODA5YmQ5ZmVkMGNiYjI1YWY5YTYiLCJpYXQiOjE3MDkzNTI3MjUsImV4cCI6MTcwOTM1NjMyNX0.NkY1Lx7Mlb72qTtE4Y9eu4rNmObxVkhsvqiKr1NO-Ew
POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: bearer {{token}}

{
  "caption": "a blue square"
}

###
# deleting a post (use the id from the one of the responses above)
# replace {{token}} with the token from the login response
# should return 204
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYmJ5ZG9iIiwiaWQiOiI2NWRhODA5YmQ5ZmVkMGNiYjI1YWY5YTYiLCJpYXQiOjE3MDkzNTI3MjUsImV4cCI6MTcwOTM1NjMyNX0.NkY1Lx7Mlb72qTtE4Y9eu4rNmObxVkhsvqiKr1NO-Ew
DELETE http://localhost:3001/api/posts/65e2a7dc58bb1d3eaacc4f89
Content-Type: application/json
Authorization: bearer {{token}}


### deleting non-existing post
# replace {{token}} with the token from the login response
# delete an existing post use its id in the url
# should return 404
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYmJ5ZG9iIiwiaWQiOiI2NWRhODA5YmQ5ZmVkMGNiYjI1YWY5YTYiLCJpYXQiOjE3MDkzNTI3MjUsImV4cCI6MTcwOTM1NjMyNX0.NkY1Lx7Mlb72qTtE4Y9eu4rNmObxVkhsvqiKr1NO-Ew
DELETE http://localhost:3001/api/posts/65e2a7dc58bb1d3eaacc4f89
Content-Type: application/json
Authorization: bearer {{token}}
